<?php

namespace b10k\componentmap\services;

use b10k\componentmap\models\Graph;

/**
 * Writes the map as Markdown: a file a coding agent (or a new developer)
 * reads before touching templates.
 *
 * Deterministic — the same project gives the same file, so two snapshots can
 * be diffed and it only changes when the templates or content model do.
 *
 * Craft-free.
 */
final class MarkdownWriter
{
    /**
     * @param string $craft How to run Craft in this project: `php craft`, `ddev craft`.
     */
    public function write(Graph $graph, string $projectName = '', string $craft = 'php craft'): string
    {
        $explorer = new Explorer($graph);
        $lines = [];

        $lines[] = '# Component map' . ($projectName !== '' ? " — {$projectName}" : '');
        $lines[] = '';
        $lines[] = "<!-- Generated by Component Map ({$craft} component-map/build). Do not edit by hand. -->";
        $lines[] = '';
        $lines[] = 'How the templates of this Craft project fit together: which template renders which page and which';
        $lines[] = 'page-builder block, and what each template includes. Before changing a template, check what it affects:';
        $lines[] = '';
        $lines[] = '```bash';
        $lines[] = "{$craft} component-map/show _blocks/hero        # a template, an entry type or a section handle";
        $lines[] = "{$craft} component-map/impact --git             # what your uncommitted changes affect";
        $lines[] = '```';
        $lines[] = '';

        $templates = $graph->nodes('template');
        $sections = $graph->nodes('section');
        $groups = $graph->nodes('categoryGroup');
        $fields = $graph->nodes('field');
        $lines[] = self::counts($graph);
        $lines[] = '';

        // Pages.
        if ($sections !== [] || $groups !== []) {
            $lines[] = '## Pages';
            $lines[] = '';
            foreach ([...$sections, ...$groups] as $id => $node) {
                $d = $explorer->describe($id);
                $type = $node['meta']['type'] ?? ($node['kind'] === 'categoryGroup' ? 'categories' : '');
                $tpls = array_map(static fn(array $t) => '`' . $t['template'] . '`', $d['templates']);
                $lines[] = sprintf(
                    '- **%s** (`%s`%s) → %s',
                    $node['label'],
                    $node['handle'] ?? $id,
                    $type !== '' ? ", {$type}" : '',
                    $tpls === [] ? '_no template_' : implode(', ', $tpls),
                );
                foreach ($d['templates'] as $t) {
                    if ($t['uses'] !== []) {
                        $lines[] = '  - uses ' . implode(', ', array_map(static fn(string $u) => "`{$u}`", $t['uses']));
                    }
                }
            }
            $lines[] = '';
        }

        // Page builders.
        if ($fields !== []) {
            $lines[] = '## Page-builder blocks';
            $lines[] = '';
            foreach ($fields as $fieldId => $field) {
                $d = $explorer->describe($fieldId);
                $lines[] = sprintf('### %s (`%s`)', $field['label'], $field['handle'] ?? $fieldId);
                $lines[] = '';
                if ($d['onEntryTypes'] !== []) {
                    $lines[] = 'On entry types: ' . implode(', ', array_map(static fn(string $h) => "`{$h}`", $d['onEntryTypes']));
                    $lines[] = '';
                }
                $lines[] = '| Block (entry type) | Rendered by | Through | Uses |';
                $lines[] = '|---|---|---|---|';
                foreach ($d['allows'] as $handle) {
                    $type = $explorer->describe('entryType:' . $handle);
                    $label = $graph->node('entryType:' . $handle)['label'] ?? $handle;
                    if ($type['renderedBy'] === []) {
                        $lines[] = sprintf('| %s (`%s`) | _no template named after it_ | | |', $label, $handle);
                        continue;
                    }
                    foreach ($type['renderedBy'] as $r) {
                        $lines[] = sprintf(
                            '| %s (`%s`) | `%s` | %s | %s |',
                            $label,
                            $handle,
                            $r['template'],
                            $r['via'] !== null ? "`{$r['via']}`" : '',
                            implode(', ', array_map(static fn(string $u) => "`{$u}`", $r['uses'])),
                        );
                    }
                }
                $lines[] = '';
            }
        }

        // Templates.
        $lines[] = '## Templates';
        $lines[] = '';
        foreach ($templates as $id => $node) {
            $d = $explorer->describe($id);
            $lines[] = '### `' . $node['label'] . '`';
            $lines[] = '';
            $lines[] = '- used by: ' . ($d['usedBy'] === [] ? '—' : implode(', ', array_map([$this, 'ref'], $d['usedBy'])));
            $lines[] = '- uses: ' . ($d['uses'] === [] ? '—' : implode(', ', array_map([$this, 'ref'], $d['uses'])));
            if ($d['renders'] !== []) {
                $lines[] = '- renders block: ' . implode(', ', array_map(
                    static fn(array $r) => '`' . $r['entryType'] . '`' . ($r['via'] ? " (via `{$r['via']}`)" : ''),
                    $d['renders'],
                ));
            }
            $affects = [];
            if ($d['affects']['entryTypes'] !== []) {
                $affects[] = 'blocks ' . implode(', ', array_map(static fn(string $h) => "`{$h}`", $d['affects']['entryTypes']));
            }
            if ($d['affects']['pages'] !== []) {
                $affects[] = 'pages ' . implode(', ', array_map(static fn(string $p) => '`' . substr($p, (int)strpos($p, ':') + 1) . '`', $d['affects']['pages']));
            }
            if ($affects !== []) {
                $lines[] = '- a change affects: ' . implode('; ', $affects);
            }
            $lines[] = '';
        }

        // Loose ends.
        $unresolved = $graph->unresolved();
        $errors = $graph->errors();
        if ($unresolved !== [] || $errors !== []) {
            $lines[] = '## Not resolved';
            $lines[] = '';
            foreach ($unresolved as $u) {
                $lines[] = sprintf('- `%s` line %d: `{%% %s %s %%}` — %s', $u['from'], $u['line'], rtrim($u['tag'], '()'), $u['expression'], $u['reason']);
            }
            foreach ($errors as $file => $error) {
                $lines[] = sprintf('- `%s`: could not be read by Twig — %s (static references were still picked up)', $file, $error);
            }
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * @param array<string, mixed> $e
     */
    private function ref(array $e): string
    {
        $flags = array_keys(array_filter([
            'dynamic' => $e['dynamic'] ?? false,
            'fallback' => $e['fallback'] ?? false,
            'conditional' => $e['conditional'] ?? false,
        ]));
        $tag = $e['tag'] === 'include' ? '' : " {$e['tag']}";
        return '`' . $e['template'] . '`' . ($tag !== '' || $flags !== [] ? ' (' . trim($tag . ' ' . implode(', ', $flags)) . ')' : '');
    }

    /**
     * “17 templates · 1 section · 4 Matrix fields · 10 entry types”
     */
    public static function counts(Graph $graph, string $separator = ' · '): string
    {
        $n = static fn(int $count, string $one, string $many): string => $count . ' ' . ($count === 1 ? $one : $many);
        return implode($separator, [
            $n(count($graph->nodes('template')), 'template', 'templates'),
            $n(count($graph->nodes('section')), 'section', 'sections'),
            $n(count($graph->nodes('field')), 'Matrix field', 'Matrix fields'),
            $n(count($graph->nodes('entryType')), 'entry type', 'entry types'),
        ]);
    }
}
